### ISSUE TITLE
[Maintainer] Issues with release v194

### ISSUE THREAD

**Issue by Cryptiiiic** [futurerestore/futurerestore#10]
- [x] **Fix Failed to enter recovery mode**
- [x] **Remove device should turn green warning message shows up on non bgcolor devices**
- [x] **Rewrite firmware updater components to not use zip ipsw**
- [x] **Fix 32bit restores(and pwned 64bit) aka pwned dfu restores**
- [x] **Improve CI**
- [x] **Current tsschecker is outdated, so merge a new updated fork**

**Comment by DanTheMann15** [comment]
i am not sure if this belongs here but since it is a futurerestore component, do you mind looking into this issue with img4tool?
https://github.com/tihmstar/img4tool/issues/50

i don't think it breaks anything but it's a windows-specific problem.

**Comment by Cryptiiiic** [comment]
@DanTheMann15 although it breaks in windows cli, the img4tool exe itself, it doesn't seem to affect futurerestore oddly enough.

**Comment by DanTheMann15** [comment]
its bizarre though. you can verify tickets and make signed iBSS/iBEC, but it can't do anything else since the cli is broken, on windows.

**Comment by opa334** [comment]
> its bizarre though. you can verify tickets and make signed iBSS/iBEC, but it can't do anything else since the cli is broken, on windows.

there is something fishy going on with the ASN1DERElement parser on windows, but I can't seem to be able to tell what part of the code would act different when it's ran on Windows

**Comment by DanTheMann15** [comment]
i recently had a thought, doesn't the SE/Savage/Yonkers/Rose/Veridian (and so on) firmwares have their own separate apnonce?
because during my test restores, i noticed that the firmware components are downloaded from the latest IPSW.

can somebody tell me more about how these special firmware components are handled, especially in regard to tss requests?

**Comment by Cryptiiiic** [comment]
Apple signs them but for some reason with iPhone 11 models they were no longer signing 14.3 but all the rest of the devices still have 14.3 signed. They are downloaded to use as a fallback incase apple isn't signing them, yes they all have a nonce they are called firmwareupdater components @DanTheMann15

**Comment by yomarion61** [comment]
Fix the notorious SEP panic FDR error when restoring to 14.2 or lower sometimes  please fix please fix please fix please fix

**Comment by Cryptiiiic** [comment]
@yomarion61 @ddavid-son ddavid-son deleted, if you pull a stunt like this again Im banning you.

**Comment by ddavid-son** [comment]
What!?! What stunt, the link clearly says report issues here , if this is not the place then you need to edit it... Anyway nothing was done with a malicious intent

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Cryptiiiic** [comment]
@DanTheMann15 I noticed with your pull that the download progress no longer shows lol, I will fix it unless you know how.

**Comment by DanTheMann15** [comment]
> 
> 
> @DanTheMann15 I noticed with your pull that the download progress no longer shows lol, I will fix it unless you know how.

I intentionally removed the progress bar because it was broken, if you can make a PR that fixes it for all platforms on my repository i will gladly merge it. = https://github.com/DanTheMann15/tsschecker

**Comment by DanTheMann15** [comment]
there is a bug with the server url feature in tsschecker, see https://github.com/1Conan/tsschecker/issues/3
