### ISSUE TITLE
Unable to place device into recovery mode from Normal mode

### ISSUE THREAD

**Issue by Robby-Sodhi** [futurerestore/futurerestore#11]
Iphone xr 13.5 going to 14.3

windows 10 
the device visibly goes into recovery mode and itunes sees that my phone is in recovery mode but future restore canno't. I am using future restore with these commands. -t, --latest-sep, --latest-baseband

**Comment by Robby-Sodhi** [comment]
I ran future restore while in recovery mode and got the -8 error so I applied the fix and it seems to be working now.....

**Comment by Cryptiiiic** [comment]
This is a prime example of what not to do as a github issue.
