### ISSUE TITLE
futurerestore-a13/a14-v189.zip

### ISSUE THREAD

**Issue by FuzzyNutz** [futurerestore/futurerestore#13]
Is there an issue with futurerestore-a13/a14-v189.zip? Just wondering if it was pulled or something kuz it’s not in the downloads section, I was able to get a copy somewhere else but just making sure there’s no problems.

Edit: scratch that the zip file is corrupted from where I got it from.

**Comment by Cryptiiiic** [comment]
@FuzzyNutz Use 194 from releases
