### ISSUE TITLE
Fails to enter restore mode

### ISSUE THREAD

**Issue by adog9712** [futurerestore/futurerestore#14]
Hi,

I have tried multiple times trying to restore my iPhone 7 Plus to iOS 14.2 using multiple versions of futurerestore on macOS. I have even tried that latest version of futurerestore. It fails to enter restore mode when sending RestoreKernelCache. Below is the log of the error.

Sending RestoreKernelCache (14803444 bytes)...
ERROR: Failed to place device in restore mode
Cleaning up...
[exception]:
what=ERROR: Unable to place device into restore mode

code=66584593
line=1016
file=futurerestore.cpp
commit count=189:
commit sha  =3786d4cd230b93f4b7ade7d0fdebd56b48fbf7a6:
Done: restoring failed!

Please help

Many thanks
Andrew Seaman

**Comment by adog9712** [comment]
Yeah you are right. Even though I dumped my blobs using a tool by @moski_dev they where invalid which is strange.

**Comment by Cryptiiiic** [comment]
You are using v189, why? We are on v194.
