### ISSUE TITLE
iPad6,3 fails to restore to iOS 14.3

### ISSUE THREAD

**Issue by UInt2048** [futurerestore/futurerestore#16]
Wi-Fi only device (iPad6,3) attempting to restore with no baseband & latest SEP

Edit: Not my log, but it was similar to this:

![](https://cdn.discordapp.com/attachments/688124783400845336/837004676801101924/unknown.png)

**Comment by conrad-mo** [comment]
@UInt2048 have u changed systemversion.plist?

**Comment by UInt2048** [comment]
@F0lkl0re No, I haven't. I was trying to upgrade from 14.2 to 14.3 with my saved blobs.

**Comment by conrad-mo** [comment]
@UInt2048 strange, i had that error when i changed systemversion.plist. Do you mind heading to #futurerestore-help in r/jailbreak discord server to talk and close this issue?

**Comment by UInt2048** [comment]
Restoring to 14.5, jailbreaking with checkra1n & setting generator, and then attempting again worked. Thanks for the help!
