### ISSUE TITLE
[Error] argument parsing failed! agrc=6 optind=4

### ISSUE THREAD

**Issue by TranMoiz** [futurerestore/futurerestore#165]
C:\Users\username\Downloads\futurerestore-Windows-x86_64-v2.0.0-Build_321-RELEASE.exe -t C:\Users\username\Blobs\2820540192890926_iPhone7,2_n61ap_12.5.7-16H81_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2 --use-pwndfu --set-nonce latest-sep --latest-baseband C:\Users\username\Downloads\iPhone_4.0_64bit_12.5.7_16H81_Restore.ipsw
Version: v2.0.0(22a5d89bdec6e1c441012d63822184c93530b7e5-321)
img4tool version: 0.197-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.91-cb10d973d0af78cc55020d4cf1187c28fad0f2a0-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[Error] argument parsing failed! agrc=8 optind=6

**Comment by m1stadev** [comment]
You forgot the dashes before the `latest-sep` option (it should be `--latest-sep`)
