### ISSUE TITLE
Adding Windows Feature to auto handle errors 8,

### ISSUE THREAD

**Issue by P5-2005** [futurerestore/futurerestore#18]
hello,
on windows 10 there is : pnputil over cli to removing driver, if you can add this to windows version will be helpful for us(windows user)

`C:\Users\BH11040>pnputil
Microsoft PnP Utility

PNPUTIL [/add-driver <...> | /delete-driver <...> |
         /export-driver <...> | /enum-drivers |
         /enum-devices [<...>] | /enum-interfaces [<...>] |
         /disable-device <...> | /enable-device <...> |
         /restart-device <...> | /remove-device <...> |
         /scan-devices [<...>] | /?]

Commands:

  /add-driver <filename.inf | *.inf> [/subdirs] [/install] [/reboot]

    Add driver package(s) into the driver store.
      /subdirs - traverse sub directories for driver packages.
      /install - install/update drivers on any matching devices.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Add driver package:
        pnputil /add-driver x:\driver.inf
      Add multiple driver packages:
        pnputil /add-driver c:\oem\*.inf
      Add and install driver package:
        pnputil /add-driver device.inf /install

  /delete-driver <oem#.inf> [/uninstall] [/force] [/reboot]

    Delete driver package from the driver store.
      /uninstall - uninstall driver package from any devices using it.
      /force - delete driver package even when it is in use by devices.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Delete driver package:
        pnputil /delete-driver oem0.inf
      Force delete driver package:
        pnputil /delete-driver oem1.inf /force

  /export-driver <oem#.inf | *> <target directory>

    Export driver package(s) from the driver store into a target directory.

    Examples:
      Export driver package:
        pnputil /export-driver oem6.inf .
      Export all driver packages:
        pnputil /export-driver * c:\backup

  /enum-drivers

    Enumerate all 3rd party driver packages in the driver store.

    Examples:
      Enumerate all OEM driver packages:
        pnputil /enum-drivers

  /disable-device <instance ID> [/reboot]

    Disable devices on the system.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Disable device:
        pnputil /disable-device "USB\VID_045E&PID_00DB\6&870CE29&0&1"

  /enable-device <instance ID> [/reboot]

    Enable devices on the system.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Enable device:
        pnputil /enable-device "USB\VID_045E&PID_00DB\6&870CE29&0&1"

  /restart-device <instance ID> [/reboot]

    Restart devices on the system.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Restart device:
        pnputil /restart-device "USB\VID_045E&PID_00DB\6&870CE29&0&1"

  /remove-device <instance ID> [/subtree] [/reboot]

    Attempt to remove a device from the system.
      /subtree - remove entire device subtree, including any child devices.
      /reboot - reboot system if needed to complete the operation.

    Examples:
      Remove device:
        pnputil /remove-device "USB\VID_045E&PID_00DB\6&870CE29&0&1"

  /scan-devices [/instanceid <instance ID>] [/async]

    Scan the system for any device hardware changes.
      /instanceid <instance ID> - scan device subtree for changes.
      /async - scan for changes asynchronously.

    Examples:
      Scan devices:
        pnputil /scan-devices

  /enum-devices [/connected | /disconnected] [/instanceid <instance ID>]
                [/class <name | GUID>] [/problem [<code>]] [/ids] [/relations]
                [/drivers]

    Enumerate all devices on the system.
      /connected | /disconnected - filter by connected devices or
                                   filter by disconnected devices.
      /instanceid <instance ID> - filter by device instance ID.
      /class <name | GUID> - filter by device class name or GUID.
      /problem [<code>] - filter by devices with problems or
                          filter by specific problem code.
      /ids - display hardware IDs and compatible IDs.
      /relations - display parent and child device relations.
      /drivers - display matching and installed drivers.

    Examples:
      Enumerate only connected devices on the system:
        pnputil /enum-devices /connected
      Enumerate device with specific instance ID:
        pnputil /enum-devices /instanceid "ACPI\PNP0A08\1"
      Enumerate all devices with specific class:
        pnputil /enum-devices /class Display
        pnputil /enum-devices /class {4d36e97d-e325-11ce-bfc1-08002be10318}
      Enumerate all devices with specific problem code:
        pnputil /enum-devices /problem 28
        pnputil /enum-devices /problem 0xA
      Enumerate all devices with problems and display hardware/compatible IDs:
        pnputil /enum-devices /problem /ids

  /enum-interfaces [/enabled | /disabled] [/class <GUID>]

    Enumerate all device interfaces on the system.
      /enabled | /disabled - filter by enabled interfaces or
                             filter by disabled interfaces.
      /class <GUID> - filter by interface class GUID.

    Examples:
      Enumerate only enabled interfaces on the system:
        pnputil /enum-interfaces /enabled
      Enumerate all interfaces with specific interface class GUID:
        pnputil /enum-interfaces /class {884b96c3-56ef-11d1-bc8c-00a0c91405dd}

  /?

    Show usage screen.`

**Comment by Cryptiiiic** [comment]
An even better concept, actually fixing the drivers in the first place instead of uninstalling them.

**Comment by P5-2005** [comment]
> 
> 
> Good idea, but wouldn’t something in practice stop this? Say, accidentally removing the wrong driver?

i tried on my side this :

pnputil /remove-device "USB\VID_05AC&PID_1281\SDOM:01_CPID:8000_CPRV:20_CPFM:03_SCEP:01_BDID:04_ECID:000000XXXXXXXACC_IBFL:1D_SRNM:[DNPRGXXXXXX]" /subtree

you must run cmd as admin to use this,i think its safe

**Comment by Tanbeer191** [comment]
You might wanna remove that as it contains your ECID and serial (if you haven’t changed it already)

**Comment by NSAntoine** [comment]
@Tanbeer191 tanbeer

**Comment by NSAntoine** [comment]
> > Good idea, but wouldn’t something in practice stop this? Say, accidentally removing the wrong driver?
> 
> i tried on my side this :
> 
> pnputil /remove-device "USB\VID_05AC&PID_1281\SDOM:01_CPID:8000_CPRV:20_CPFM:03_SCEP:01_BDID:04_ECID:000000XXXXXXXACC_IBFL:1D_SRNM:[DNPRGXXXXXX]" /subtree
> 
> you must run cmd as admin to use this,i think its safe

Is there a way to test this in practice?

**Comment by P5-2005** [comment]
> 
> 
> > > Good idea, but wouldn’t something in practice stop this? Say, accidentally removing the wrong driver?
> > 
> > 
> > i tried on my side this :
> > pnputil /remove-device "USB\VID_05AC&PID_1281\SDOM:01_CPID:8000_CPRV:20_CPFM:03_SCEP:01_BDID:04_ECID:000000XXXXXXXACC_IBFL:1D_SRNM:[DNPRGXXXXXX]" /subtree
> > you must run cmd as admin to use this,i think its safe
> 
> Is there a way to test this in practice?

i will do it tomorrow with my test device and tell you the result

**Comment by Tanbeer191** [comment]
![image](https://user-images.githubusercontent.com/67960712/120898541-30370800-c623-11eb-875c-4f72f18fdbe0.png)

can confirm this works on my end

**Comment by Tanbeer191** [comment]
the only problem with this now is fixing -8 for the majority of people is not as simple as removing drivers, sometimes re-installing iTunes (specific version) is required, sometimes you need to restart to get back the drivers etc.

**Comment by NSAntoine** [comment]
Hold on, what’s the specific version?

**Comment by Tanbeer191** [comment]
https://support.apple.com/kb/DL1816?locale=en_GB

**Comment by NSAntoine** [comment]
Well, can’t fr just re install iTunes, then?

**Comment by Tanbeer191** [comment]
Like I said, it’s not the same for every user, more steps may be required, and it would be getting dangerously out of scope for a device restoring program.

**Comment by P5-2005** [comment]
> 
> 
> the only problem with this now is fixing -8 for the majority of people is not as simple as removing drivers, sometimes re-installing iTunes (specific version) is required, sometimes you need to restart to get back the drivers etc.

i think you can confirm this if the device will get the ibec error or not when device is on rec mode, if there is the driver issue on device manager you can see iBoot : 

USB\VID_05AC&PID_1281\SDOM:01_CPID:8000_CPRV:20_CPFM:03_SCEP:01_BDID:04_ECID:000000XXXXXXXACC_IBFL:1D_SRNM:[DNPRGXXXXXX]"

but if the good driver is there on rec mode you will see this value :

USB\VID_05AC&PID_12A8\ffffffffffffffffffffffffffffffffffffffff

you can confirm this with this : pnputil /enum-devices | find "USB\VID_05AC&PID_12A8\ffffffffffffffffffffffffffffffffffffffff"

> 
> 
> the only problem with this now is fixing -8 for the majority of people is not as simple as removing drivers, sometimes re-installing iTunes (specific version) is required, sometimes you need to restart to get back the drivers etc.

only if they install itunes from web you can do this method, if they install from windows store here they need to reinstall from web not from windows store

**Comment by Tanbeer191** [comment]
and what happens if the good driver is not found even after removing the bad driver and the win32 iTunes is installed? this would probably be common. but i agree, this would fix ibec in some cases.

**Comment by P5-2005** [comment]
i tried today to automate the script find the right instance id of driver and the file of driver then remove : 

```
@ECHO OFF
SETLOCAL ENABLEEXTENSIONS
SETLOCAL DISABLEDELAYEDEXPANSION

FOR /F "skip=1 " %%i IN ('wmic PATH CIM_LogicalDevice where 'Description like 'Apple%%'' get /value ^| findstr /B  "DeviceID=USB\\"') DO ECHO %%i > null && SET var=%%i
set var=%var:&amp;=^&%

:: we get instance id of iBoot Driver

FOR /F "tokens=* USEBACKQ" %%F IN (`pnputil /enum-devices /instanceid "%var:~9%" ^| findstr oem`) DO (
SET oemnum=%%F
)
:: we get driver file of iBoot to remove

pnputil /remove-device "%var:~9%" /subtree
pnputil /delete-driver "%oemnum:~28%" /uninstall /force
```
if you need to see the value just switch off to on.
btw tried on my side worked(my itunes is from web not from store), on two pc(one desktop win10, other laptoop win10)

**Comment by P5-2005** [comment]
> 
> 
> and what happens if the good driver is not found even after removing the bad driver and the win32 iTunes is installed? this would probably be common. but i agree, this would fix ibec in some cases.

there is option on Chinese Spyware Tools to repair driver of itunes, most used and commun and too handy i think(for me) xD

**Comment by Tanbeer191** [comment]
> there is option on Chinese Spyware Tools to repair driver of itunes, most used and commun and too handy i think(for me) xD

that's interesting, would have to look into exactly what it does

**Comment by NSAntoine** [comment]
Is it known how Chinese Spyware Tools does it?

**Comment by Tanbeer191** [comment]
> > there is option on 3utools to repair driver of itunes, most used and commun and too handy i think(for me) xD
that's interesting, would have to look into exactly what it does

**Comment by Tanbeer191** [comment]
> there is option on 3utools to repair driver of itunes, most used and commun and too handy i think(for me) xD

that's interesting, would have to look into exactly what it does

**Comment by P5-2005** [comment]
> 
> 
> Is it known how 3utools does it?

![3utools](https://user-images.githubusercontent.com/36075275/120933199-f2a0b080-c6f0-11eb-889b-4155c107c416.png)

**Comment by NSAntoine** [comment]
@P5-2005 i meant, the actual process itself, lol

**Comment by P5-2005** [comment]
> 
> 
> @P5-2005 i meant, the actual process itself, lol

btw, every time using future restore, first time cannot put device on recovery mode when on normal mode even the device is trusted, so i use Chinese Spyware Tools to put on recovery or with mobiledevice framework xD, then go back to future restore

**Comment by Tanbeer191** [comment]
> btw, every time using future restore, first time cannot put device on recovery mode when on normal mode even the device is trusted, so i use Chinese Spyware Tools to put on recovery or with mobiledevice framework xD, then go back to future restore

apple introduced new recovery mode checks in ios 14.5+, someone needs to update the idevicerestore module in futurerestore to enter recovery mode successfully, until then you need to enter recovery mode manually

**Comment by NSAntoine** [comment]
Didn’t @nyuszika7h do that on 204/8?

**Comment by P5-2005** [comment]
> 
> 
> > btw, every time using future restore, first time cannot put device on recovery mode when on normal mode even the device is trusted, so i use Chinese Spyware Tools to put on recovery or with mobiledevice framework xD, then go back to future restore
> 
> apple introduced new recovery mode checks in ios 14.5+, someone needs to update the idevicerestore module in futurerestore to enter recovery mode successfully, until then you need to enter recovery mode manually

ah i forget about that even checkra1n have this issue before updating the framework when 14.5+

**Comment by ghost** [comment]
Yeah, but at least on Linux it still hangs after entering recovery and you
have to Ctrl+C and run it again.

**Comment by Tanbeer191** [comment]
> Didn’t @nyuszika7h do that on 204/8?

different branch

**Comment by NSAntoine** [comment]
@P5-2005 Hey, hakim, why don’t you join w us in the rjb discord to talk abt this?

**Comment by NSAntoine** [comment]
> Yeah, but at least on Linux it still hangs after entering recovery and you have to Ctrl+C and run it again.
> […](#)

Any implementation made to windows or macOS yet, then?

**Comment by Tanbeer191** [comment]
> > Yeah, but at least on Linux it still hangs after entering recovery and you have to Ctrl+C and run it again.
> > […](#)
> 
> Any implementation made to windows or macOS yet, then?

libimobile is cross-platform, we don't need to make any other changes, other than just compiling it for that OS

**Comment by NSAntoine** [comment]
I think cryptic sent a 204 or something macOS build once hold on

**Comment by Tanbeer191** [comment]
> i tried today to automate the script find the right instance id of driver and the file of driver then remove :
> 
> ```
> @ECHO OFF
> SETLOCAL ENABLEEXTENSIONS
> SETLOCAL DISABLEDELAYEDEXPANSION
> 
> FOR /F "skip=1 " %%i IN ('wmic PATH CIM_LogicalDevice where 'Description like 'Apple%%'' get /value ^| findstr /B  "DeviceID=USB\\"') DO ECHO %%i > null && SET var=%%i
> set var=%var:&amp;=^&%
> 
> :: we get instance id of iBoot Driver
> 
> FOR /F "tokens=* USEBACKQ" %%F IN (`pnputil /enum-devices /instanceid "%var:~9%" ^| findstr oem`) DO (
> SET oemnum=%%F
> )
> :: we get driver file of iBoot to remove
> 
> pnputil /remove-device "%var:~9%" /subtree
> pnputil /delete-driver "%oemnum:~28%" /uninstall /force
> ```
> 
> if you need to see the value just switch off to on.
> btw tried on my side worked(my itunes is from web not from store), on two pc(one desktop win10, other laptoop win10)

works on my end

**Comment by P5-2005** [comment]
> 
> 
> @P5-2005 Hey, hakim, why don’t you join w us in the rjb discord to talk abt this?
where i can find the link to discord?

**Comment by NSAntoine** [comment]
discord.gg/jb, we normally speak in the FutureRestore help chat

**Comment by P5-2005** [comment]
> 
> 
> > there is option on 3utools to repair driver of itunes, most used and commun and too handy i think(for me) xD
> 
> that's interesting, would have to look into exactly what it does

today i was bored, so i checked how spyware chinesse tool on windows no need itunes to be installed xD
from itunes.exe extract only this by OS arch, no need to install itunes from web or store : 
- AppleMobileDeviceSupport.msi
- Bonjour.msi

then install it :D

![win10-no itunes](https://user-images.githubusercontent.com/36075275/124949600-9d1a3500-e009-11eb-92f3-961b67e89287.png)
with that someone must just add libimobiledevice library working one for 14.5+ :p

![check-process-noitunes](https://user-images.githubusercontent.com/36075275/124952232-f71bfa00-e00b-11eb-952e-a778529188f9.png)

**Comment by P5-2005** [comment]
how to check it first place :: 

![check-port-and-service](https://user-images.githubusercontent.com/36075275/124963069-46b3f300-e017-11eb-8f38-73d5c021693f.png)
