### ISSUE TITLE
Stuck at "Waiting for message from FDR..."

### ISSUE THREAD

**Issue by Milchkarl** [futurerestore/futurerestore#19]
I've tried to use the program to update my iPhone 7 GSM/ iPhone 9.3 from iOS 12.4 to iOS 14.3 and its stuck at the message "FDR 00000000044964c0 waiting for message..." and after that "FDR 00000000044964c0 timeout waiting for command". Even after restartig the restoring process or after letting it do its thing for 10 minutes hoping that it would eventually just work. I couldn't find anything on the internet to fix this.

**Comment by Cryptiiiic** [comment]
For future reference, it’s generally always better if you provide as much information as possible. Doing so will help all parties involved, including the maintainer trying to help you and including yourself. For example, that warning is just the end of that log, we don’t know if some prior restore step failed in someway, or what arguments you used to begin the restore process. There is simply not enough information for us to help you or fix the issue at the moment.

**Comment by Cryptiiiic** [comment]
Closing due to no reply in a week, I stated I need more information, none was given.
