### ISSUE TITLE
Failed restore iPhone 11 to iOS 14.2 from iOS 14.2

### ISSUE THREAD

**Issue by tolikes** [futurerestore/futurerestore#27]
Here log file, I lost the jailbreak this is sad lol

i hope this log  help you 
[Terminal.log](https://github.com/m1stadev/futurerestore/files/6859247/Terminal.log)

**Comment by Cryptiiiic** [comment]
@tolikes  did you rootfs restore your jailbreak first before futurerestoring. It seems it may be a requirement for 14.2 restores for some odd reason.

**Comment by tolikes** [comment]
well, I did not know what to do, since I successfully restored the iphone 7 to ios 14.2 and I thought it would work the same way on my ip11

Thanks you for feedback!

**Comment by Cryptiiiic** [comment]
@tolikes then it seems exclusive to a12-a14
