### ISSUE TITLE
FDR unable to connect on A9. iOS 15.0.1, latest BB and SEP

### ISSUE THREAD

**Issue by Babyyoda777** [futurerestore/futurerestore#39]
`restore_is_current_device: Connected to com.apple.mobile.restored, version 15
Connecting to FDR client at port 1082
About to do ctrl handshake
FDR sending 89 bytes:
FDR Sent 89 bytes
FDR Received 105 bytes
Ctrl handshake done (ConnPort = 49159)
FDR 0000000003c0aaf0 waiting for message...
DEBUG: tss_response_get_path_by_entry: No entry 'LLB' in TSS response
NOTE: Could not get LLB path from TSS data, will fetch from build identity
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
idevice_event_cb: device (udid: ffffffffffffffffffffffffffffffff00000004) disconnected
ERROR: Unable to receive message from FDR 0000000003c0aaf0 (-2). 0/2 bytes
FDR 0000000003c0aaf0 terminating...
ERROR: Could not read data (-256). Aborting.
irecv_event_cb: device  (udid: ffffffffffffffffffffffffffffffff00000004) connected in Recovery mode`

Windows 11
Tried all three usb ports on my laptop. 2x USBA and 1x USBC

**Comment by Cryptiiiic** [comment]
This is a 194 issue, closing. I’ll try to push beta for windows soon sorry.
